# Generated by Django 3.0.3 on 2020-04-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='firstName',
        ),
    ]
