# Generated by Django 3.0.3 on 2020-04-09 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_remove_students_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='fistName',
        ),
        migrations.AddField(
            model_name='students',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
